networks:
  rheum-network:
    name: rheum-network
    driver: bridge

services:
  rheum:
    build: .
    image: gajdaltd/rheum:latest
    container_name: rheum
    ports:
      - "5080:5080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    depends_on:
      rhubarb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - rheum-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rhubarb:
    image: gajdaltd/rhubarb:latest
    container_name: rhubarb
    ports:
      - "5180:5080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - rheum-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  kafka:
    build:
      context: .
      dockerfile: kafka.Dockerfile
    image: gajdaltd/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_NODE_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OPTS: "-javaagent:/opt/otel-javaagent.jar"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://host.docker.internal:4318"
      OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
      OTEL_LOGS_EXPORTER: "otlp"
      OTEL_METRICS_EXPORTER: "otlp"
      OTEL_SERVICE_NAME: "kafka"
      OTEL_TRACES_EXPORTER: "otlp"
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - rheum-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
